services:
  entry:
    build: .
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
  api:
    image: chamber6821/kosox-api
    environment:
      - DB_URL=mysql://user:password@mysql/db
    expose:
      - 8080
  web:
    image: chamber6821/kosox-web
    expose:
      - 80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
