services:
  entry:
    build: .
    ports:
      - 80:80
  adminer:
    image: adminer
    ports:
      - 8080:8080
  api:
    image: chamber6821/kosox-api
    environment:
      - DB_URL=mysql://user:password@mysql/db
    expose:
      - 8080
  web:
    image: chamber6821/kosox-web
    expose:
      - 80
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
